COLORS = (
    ('amarelo', 'amarelo'),
    ('azul', 'azul'),
    ('branco', 'branco'),
    ('cinza', 'cinza'),
    ('coral', 'coral'),
    ('dourado', 'dourado'),
    ('estampado', 'estampado'),
    ('laranja', 'laranja'),
    ('marrom', 'marrom'),
    ('nude', 'nude'),
    ('prata', 'prata'),
    ('preto', 'preto'),
    ('rosa', 'rosa'),
    ('roxo', 'roxo'),
    ('verde', 'verde'),
    ('vermelho', 'vermelho'),
    ('vinho', 'vinho'),
)
