# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Aluguel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer', verbose_name='cliente')),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Dress', verbose_name='vestido')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name_plural': 'pedidos',
                'verbose_name': 'pedido',
            },
        ),
    ]
